PRINT '';
PRINT '*** Dropping Database';
GO

IF DB_ID('TaiPan') NOT NULL
    DROP DATABASE [TaiPan];

-- If the database has any other open connections close the network connection.
IF @@ERROR = 3702 
    RAISERROR('[TaiPan] database cannot be dropped because there are still other open connections', 127, 127) WITH NOWAIT, LOG;
GO

CREATE DATABASE [TaiPan] ON PRIMARY 
( NAME = N'TaiPan', FILENAME = N'F:\Program Files\Microsoft SQL Server\MSSQL10.SQLEXPRESS\MSSQL\DATA\TaiPan.mdf' , SIZE = 3072KB , FILEGROWTH = 1024KB )
LOG ON 
( NAME = N'TaiPan_log', FILENAME = N'F:\Program Files\Microsoft SQL Server\MSSQL10.SQLEXPRESS\MSSQL\DATA\TaiPan_log.ldf' , SIZE = 1024KB , FILEGROWTH = 10%)
GO
ALTER DATABASE [TaiPan] SET COMPATIBILITY_LEVEL = 100
GO
ALTER DATABASE [TaiPan] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [TaiPan] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [TaiPan] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [TaiPan] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [TaiPan] SET ARITHABORT OFF 
GO
ALTER DATABASE [TaiPan] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [TaiPan] SET AUTO_CREATE_STATISTICS ON 
GO
ALTER DATABASE [TaiPan] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [TaiPan] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [TaiPan] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [TaiPan] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [TaiPan] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [TaiPan] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [TaiPan] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [TaiPan] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [TaiPan] SET  DISABLE_BROKER 
GO
ALTER DATABASE [TaiPan] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [TaiPan] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [TaiPan] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [TaiPan] SET  READ_WRITE 
GO
ALTER DATABASE [TaiPan] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [TaiPan] SET  MULTI_USER 
GO
ALTER DATABASE [TaiPan] SET PAGE_VERIFY CHECKSUM  
GO
USE [TaiPan]
GO
IF NOT EXISTS (SELECT name FROM sys.filegroups WHERE is_default=1 AND name = N'PRIMARY') ALTER DATABASE [TaiPan] MODIFY FILEGROUP [PRIMARY] DEFAULT
GO

PRINT '';
PRINT '*** Database created';