CREATE DATABASE [taipan] ON  PRIMARY 
( NAME = N'taipan', FILENAME = N'F:\Program Files\Microsoft SQL Server\MSSQL10.SQLEXPRESS\MSSQL\DATA\taipan.mdf' , SIZE = 3072KB , FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'taipan_log', FILENAME = N'F:\Program Files\Microsoft SQL Server\MSSQL10.SQLEXPRESS\MSSQL\DATA\taipan_log.ldf' , SIZE = 1024KB , FILEGROWTH = 10%)
GO
ALTER DATABASE [taipan] SET COMPATIBILITY_LEVEL = 100
GO
ALTER DATABASE [taipan] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [taipan] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [taipan] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [taipan] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [taipan] SET ARITHABORT OFF 
GO
ALTER DATABASE [taipan] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [taipan] SET AUTO_CREATE_STATISTICS ON 
GO
ALTER DATABASE [taipan] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [taipan] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [taipan] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [taipan] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [taipan] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [taipan] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [taipan] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [taipan] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [taipan] SET  DISABLE_BROKER 
GO
ALTER DATABASE [taipan] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [taipan] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [taipan] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [taipan] SET  READ_WRITE 
GO
ALTER DATABASE [taipan] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [taipan] SET  MULTI_USER 
GO
ALTER DATABASE [taipan] SET PAGE_VERIFY CHECKSUM  
GO
USE [taipan]
GO
IF NOT EXISTS (SELECT name FROM sys.filegroups WHERE is_default=1 AND name = N'PRIMARY') ALTER DATABASE [taipan] MODIFY FILEGROUP [PRIMARY] DEFAULT
GO